# Generated by Django 3.2.9 on 2021-11-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('type', models.CharField(choices=[('m', 'Материалы'), ('t', 'Инструменты')], max_length=1)),
                ('measure', models.CharField(choices=[('kg', 'Килограмм'), ('kk', 'Тонна'), ('m3', 'Кубометр'), ('m2', 'Квадратный метр'), ('pm', 'Погонный метр'), ('pc', 'Штука'), ('2p', 'Пара')], max_length=2)),
            ],
            options={
                'verbose_name': 'Материал/инструмент',
                'verbose_name_plural': 'Материалы/инструменты',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.goods')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
    ]
