# Generated by Django 3.2.9 on 2021-11-30 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_details_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Пусто', verbose_name='Примечание')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Пусто', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Пусто', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пг.м'), ('pc', 'шт.'), ('2p', 'пар.')], max_length=2),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.TextField(default='Пусто', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.TextField(default='Пусто', verbose_name='Примечание'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Пусто', verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('type', models.CharField(choices=[('m', 'Материалы'), ('w', 'Работа'), ('t', 'Техника'), ('d', 'Доставка')], max_length=1)),
                ('cash', models.CharField(choices=[('y', 'Безнал'), ('n', 'Нал')], max_length=1)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measure', models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пг.м'), ('pc', 'шт.'), ('2p', 'пар.')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(verbose_name='Описание')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.bid')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.house')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.object'),
        ),
        migrations.AddField(
            model_name='bid',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
