# Generated by Django 3.2.9 on 2021-11-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20211130_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.object'),
            preserve_default=False,
        ),
    ]
