# Generated by Django 3.2.9 on 2021-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пг.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('hh', 'час.'), ('--', 'доставка')], max_length=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
