# Generated by Django 3.2.9 on 2021-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20211201_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Заблокировано'),
        ),
    ]
