# Generated by Django 3.2.9 on 2021-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_bid_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
