# Generated by Django 3.2.9 on 2021-12-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_content_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Пусто', verbose_name='Описание')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.bid')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
            },
        ),
    ]
