# Generated by Django 3.2.9 on 2021-12-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='bid',
        ),
    ]
