# Generated by Django 3.2.9 on 2021-12-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_phase_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='phase',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='project.phase'),
            preserve_default=False,
        ),
    ]
