# Generated by Django 3.2.9 on 2021-12-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_bid_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='content',
            name='cash',
            field=models.CharField(choices=[('y', 'Нал'), ('n', 'Безнал')], max_length=1),
        ),
    ]
