# Generated by Django 3.2.9 on 2021-12-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20211207_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.supplier'),
            preserve_default=False,
        ),
    ]
