# Generated by Django 3.2.9 on 2021-12-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_content_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='supplier',
        ),
    ]
