# Generated by Django 3.2.9 on 2021-12-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_rename_content_content_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='phase',
        ),
        migrations.AddField(
            model_name='content',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.phase'),
            preserve_default=False,
        ),
    ]
