# Generated by Django 3.2.9 on 2021-12-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='estimate',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='project.estimate'),
            preserve_default=False,
        ),
    ]
