# Generated by Django 3.2.9 on 2021-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_content_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
