# Generated by Django 3.2.9 on 2021-12-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_bid_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
