# Generated by Django 3.2.9 on 2021-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
