# Generated by Django 3.2.9 on 2021-12-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_content_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='number',
            field=models.IntegerField(default=0, max_length=6, verbose_name='Номер заявки'),
        ),
    ]
