# Generated by Django 3.2.9 on 2022-02-16 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0025_auto_20211216_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пг.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('hh', 'час.'), ('lt', 'л.'), ('hu', 'чел.'), ('--', 'доставка')], max_length=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('a', 'Материалы'), ('b', 'Работа'), ('c', 'Техника'), ('d', 'Доставка'), ('e', 'Перемещение'), ('f', 'Прочие расходы')], max_length=1),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(default='0', verbose_name='Номер заявки')),
                ('title', models.TextField(default='Пусто', verbose_name='Примечание')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Помечено')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Архивная заявка',
                'verbose_name_plural': 'Архивные заявки',
            },
        ),
    ]
