# Generated by Django 3.2.9 on 2022-02-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20220216_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Пусто', verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('cash', models.CharField(choices=[('y', 'Нал'), ('n', 'Безнал')], max_length=1)),
                ('summary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('supplier', models.TextField(blank=True, null=True, verbose_name='Поставщик')),
                ('spending', models.TextField(blank=True, null=True, verbose_name='Поставщик')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Материалы')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('measure', models.CharField(blank=True, max_length=8, null=True)),
                ('foreman', models.TextField(blank=True, null=True, verbose_name='Прораб')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.archive')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.estimate')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.house')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.phase')),
            ],
            options={
                'verbose_name': 'Позиция архивной заявки',
                'verbose_name_plural': 'Позиции архивной заявки',
            },
        ),
    ]
