# Generated by Django 3.2.9 on 2022-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_archivedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='number',
            field=models.TextField(default='0', verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='content',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пг.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('hh', 'час.'), ('lt', 'л.'), ('hu', 'чел.'), ('on', 'ед.'), ('--', 'доставка')], max_length=2),
        ),
    ]
