# Generated by Django 3.2.9 on 2022-04-22 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0028_auto_20220322_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('hh', 'час.'), ('lt', 'л.'), ('hu', 'чел.'), ('on', 'ед.'), ('ms', 'машина'), ('--', 'доставка')], max_length=2),
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Пусто', verbose_name='Комментарий')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('summary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'verbose_name': 'Авансовый платёж',
                'verbose_name_plural': 'Авансовые платежи',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Пусто', verbose_name='Комментарий')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pumpcomment', models.TextField(blank=True, default='', verbose_name='Бетононасос')),
                ('pumpsummary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deliveryvolume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deliveryprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concrete_grade', models.CharField(choices=[('a', '300'), ('b', '350')], max_length=1)),
                ('pile', models.TextField(blank=True, default='', verbose_name='Информация')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.house')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.supplier')),
            ],
            options={
                'verbose_name': 'Заливка бетона',
                'verbose_name_plural': 'Заливки бетона',
            },
        ),
    ]
