# Generated by Django 3.2.9 on 2022-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20220422_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
