# Generated by Django 3.2.9 on 2022-05-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedetail',
            name='new_supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.supplier'),
            preserve_default=False,
        ),
    ]
