# Generated by Django 3.2.9 on 2022-06-10 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0033_auto_20220606_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledetail',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('bx', 'упак'), ('lt', 'л.'), ('mt', 'мл.'), ('on', 'ед.'), ('ms', 'машина')], max_length=2),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('date', models.DateTimeField(editable=False, verbose_name='Дата создания')),
                ('lastdate', models.DateTimeField(editable=False, verbose_name='Дата последнего статуса')),
                ('status', models.CharField(choices=[('0', 'Создан'), ('1', 'У руководителя'), ('2', 'У снабженца'), ('3', 'У бухгалтера'), ('4', 'Поставка'), ('5', 'Завершён')], max_length=1)),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.house')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sample')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
