# Generated by Django 3.2.9 on 2022-06-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20220610_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='Комментарий')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('measure', models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('bx', 'упак'), ('lt', 'л.'), ('mt', 'мл.'), ('on', 'ед.'), ('ms', 'машина')], max_length=2)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.order')),
            ],
            options={
                'verbose_name': 'Деталь заказа',
                'verbose_name_plural': 'Детали заказа',
            },
        ),
    ]
