# Generated by Django 3.2.9 on 2022-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='sample_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
