# Generated by Django 3.2.9 on 2022-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20220621_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Сверено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Создан'), ('1', 'У руководителя'), ('2', 'У снабженца'), ('3', 'У бухгалтера'), ('4', 'Поставка'), ('5', 'Доставлено полностью'), ('6', 'Не доставлено/есть замечания'), ('7', 'Завершён')], max_length=1),
        ),
    ]
