# Generated by Django 3.2.9 on 2022-10-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cash',
            field=models.CharField(choices=[('y', 'Нал'), ('n', 'Безнал'), ('b', 'Бартер')], max_length=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('bx', 'упак'), ('hh', 'час.'), ('lt', 'л.'), ('mt', 'мл.'), ('hu', 'чел.'), ('on', 'ед.'), ('ms', 'машина'), ('--', 'доставка')], max_length=2),
        ),
    ]
