# Generated by Django 3.2.9 on 2022-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20221017_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто'),
        ),
        migrations.AlterField(
            model_name='content',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('bx', 'упак'), ('hh', 'час.'), ('lt', 'л.'), ('mt', 'мл.'), ('hu', 'чел.'), ('on', 'ед.'), ('ms', 'машина'), ('st', 'комплект'), ('--', 'доставка')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('bx', 'упак'), ('lt', 'л.'), ('mt', 'мл.'), ('on', 'ед.'), ('ms', 'машина'), ('st', 'комплект')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sampledetail',
            name='measure',
            field=models.CharField(choices=[('kg', 'кг'), ('kk', 'т.'), ('m1', 'м.'), ('m3', 'м3'), ('m2', 'кв.м'), ('pm', 'пог.м'), ('pc', 'шт.'), ('2p', 'пар.'), ('bx', 'упак'), ('lt', 'л.'), ('mt', 'мл.'), ('on', 'ед.'), ('ms', 'машина'), ('st', 'комплект')], max_length=2),
        ),
    ]
