# Generated by Django 3.2.9 on 2022-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20221112_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
