# Generated by Django 3.2.9 on 2022-12-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_content_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedetail',
            name='history',
            field=models.TextField(blank=True, default='', null=True, verbose_name='История изменений'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='history',
            field=models.TextField(blank=True, default='', null=True, verbose_name='История изменений'),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='history',
            field=models.TextField(blank=True, default='', null=True, verbose_name='История изменений'),
        ),
    ]
