# Generated by Django 3.2.9 on 2023-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20221210_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='supervision',
            field=models.BooleanField(default=False, verbose_name='Техконтроль'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Подписано'),
        ),
    ]
