# Generated by Django 3.2.9 on 2023-01-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20230124_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='supervisor',
            field=models.TextField(default='', verbose_name='Контролёр'),
        ),
    ]
