# Generated by Django 3.2.9 on 2023-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_alter_subcash_closedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcash',
            name='closedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
