# Generated by Django 3.2.9 on 2023-04-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20230430_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AddField(
            model_name='content',
            name='subcash',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.subcash'),
        ),
    ]
