# Generated by Django 3.2.9 on 2023-05-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='credit_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account2', to='project.account'),
        ),
        migrations.AddField(
            model_name='content',
            name='expense_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_account2', to='project.account'),
        ),
    ]
