# Generated by Django 3.2.9 on 2023-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_earning_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earning',
            name='price',
        ),
        migrations.AddField(
            model_name='earning',
            name='summary',
            field=models.DecimalField(decimal_places=2, default=1001, max_digits=12, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
