# Generated by Django 3.2.9 on 2023-05-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_auto_20230506_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.supplier'),
            preserve_default=False,
        ),
    ]
