# Generated by Django 3.2.9 on 2023-05-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_earning_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.supplier'),
        ),
    ]
