# Generated by Django 3.2.9 on 2023-06-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0060_alter_earning_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('client', models.TextField(default='', verbose_name='Клиент')),
                ('agency', models.TextField(default='', verbose_name='Агентство/агент/менеджер')),
                ('apartment', models.TextField(default='', verbose_name='Апартамент')),
                ('square', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Площадь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена по шахматке')),
                ('agency_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка АН')),
                ('developer_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка застройщика')),
                ('seller_commission_calc', models.TextField(default='', verbose_name='Расчет комиссии Эксклюзив')),
                ('seller_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия Эксклюзив')),
                ('agency_commission_calc', models.TextField(default='', verbose_name='Расчет комиссии АН')),
                ('agency_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия АН')),
                ('installment', models.TextField(blank=True, default='', null=True, verbose_name='Срок рассрочки')),
                ('status', models.CharField(choices=[('a', 'Создан'), ('b', 'На исполнении'), ('c', 'Исполнен')], max_length=1)),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.house')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.object')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
