# Generated by Django 3.2.9 on 2023-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0061_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='prepaid',
            field=models.BooleanField(default=False, verbose_name='Оплата после доставки'),
        ),
    ]
