# Generated by Django 3.2.9 on 2023-06-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_content_prepaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата совершения операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('type', models.IntegerField(choices=[(1, 'Бронь'), (2, 'Поступление оплаты'), (100, 'Выплата комиссии Эксклюзив'), (101, 'Выплата комиссии АН')], default=2, verbose_name='Тип операции')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('performed', models.BooleanField(default=False, verbose_name='Проведена')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.contract')),
            ],
            options={
                'verbose_name': 'Операция по контракту',
                'verbose_name_plural': 'Операции по контракту',
            },
        ),
    ]
