# Generated by Django 3.2.9 on 2023-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_turnover_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.TextField(default='0', verbose_name='Номер контракта'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('a', 'ДИ'), ('b', 'ДБ'), ('c', 'ДКП')], default='a', max_length=1),
        ),
    ]
