# Generated by Django 3.2.9 on 2023-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20230701_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnover',
            name='actualdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Реальная дата совершения операции'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('a', 'Создан'), ('b', 'Проверен бухгалтером'), ('c', 'На исполнении'), ('d', 'Исполнен')], max_length=1),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='date',
            field=models.DateTimeField(verbose_name='Планируемая дата совершения операции'),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='type',
            field=models.IntegerField(choices=[(1, 'Бронь'), (2, 'Поступление оплаты'), (100, 'Выплата комиссии ОП'), (101, 'Выплата комиссии АН')], default=2, verbose_name='Тип операции'),
        ),
    ]
