# Generated by Django 3.2.9 on 2023-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20230717_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='onhand',
            field=models.BooleanField(default=False, verbose_name='Оригинал в наличии'),
        ),
        migrations.AddField(
            model_name='contract',
            name='receipt',
            field=models.BooleanField(default=False, verbose_name='Чек отбит'),
        ),
    ]
