# Generated by Django 3.2.9 on 2023-08-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_auto_20230720_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('image', models.ImageField(upload_to='images')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.contract')),
            ],
        ),
    ]
