# Generated by Django 3.2.9 on 2023-08-17 20:15

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_contractimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='object',
            name='special',
            field=models.BooleanField(default=True, verbose_name='Использовать в заявках'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='seller_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Комиссия ОП'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='seller_commission_calc',
            field=models.TextField(default='', verbose_name='Расчет комиссии ОП'),
        ),
        migrations.AlterField(
            model_name='contractimage',
            name='image',
            field=models.ImageField(upload_to=project.models.path_and_rename_image),
        ),
    ]
