# Generated by Django 3.2.9 on 2023-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_auto_20230817_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыта'),
        ),
    ]
