# Generated by Django 3.2.9 on 2024-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_auto_20231027_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='reservation_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата виртуального бронирования'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reservation_type',
            field=models.CharField(choices=[('a', 'Нет брони'), ('b', 'Запрос виртуального бронирования'), ('c', 'Забронировано')], default='a', max_length=1),
        ),
    ]
